### ISSUE TITLE
Register a file type

### ISSUE THREAD

**Issue by lukeribchester** [lukeribchester/pact-intellij#1]
# Description

Register an IntelliJ Platform file type to associate the `.pact` file extension with the Pact language.

# Tasks

- [x] Define the language
- [x] Define an icon
- [x] Define a file type

# Resources

- Custom Language Support / [Registering a File Type](https://plugins.jetbrains.com/docs/intellij/registering-file-type.html)
- Custom Language Support Tutorial / [2. Language and File Type](https://plugins.jetbrains.com/docs/intellij/language-and-filetype.html)
