### ISSUE TITLE
Generate a parser

### ISSUE THREAD

**Issue by lukeribchester** [lukeribchester/pact-intellij#2]
# Description

Generate an IntelliJ Platform language parser from the Pact grammar definition.

# Tasks

- [x] Define a token type
- [x] Define an element type
- [x] Define the Pact grammar
- [x] Generate a parser

# Resources

- Custom Language Support / [Implementing Lexer﻿](https://plugins.jetbrains.com/docs/intellij/implementing-lexer.html)
- Custom Language Support / [Implementing Parser and PSI﻿](https://plugins.jetbrains.com/docs/intellij/implementing-parser-and-psi.html)
- Custom Language Support Tutorial / [3. Grammar and Parser﻿](https://plugins.jetbrains.com/docs/intellij/grammar-and-parser.html)
