### ISSUE TITLE
Define a lexer and parser

### ISSUE THREAD

**Issue by lukeribchester** [lukeribchester/pact-intellij#3]
# Description

Define a lexical analyser using [JFlex](https://jflex.de) and define the parser generated in #2.

# Tasks

- [x] Define a lexer
- [x] Generate a lexer class
- [x] Define a lexer adapter
- [x] Define a root file
- [x] Define a set of token types
- [x] Define a parser
- [x] Register the parser definition

# Resources

- Custom Language Support / [Implementing Lexer﻿](https://plugins.jetbrains.com/docs/intellij/implementing-lexer.html)
- Custom Language Support Tutorial / [4. Lexer and Parser﻿ Definition](https://plugins.jetbrains.com/docs/intellij/lexer-and-parser-definition.html)
