### ISSUE TITLE
Define a syntax highlighter

### ISSUE THREAD

**Issue by lukeribchester** [lukeribchester/pact-intellij#4]
# Description

Define a syntax highlighter and colour settings page.

# Tasks

- [x] Define a syntax highlighter
- [x] Define a syntax highlighter factory
- [x] Register the syntax highlighter factory
- [x] Define a colour settings page
- [x] Register the colour settings page

# Resources

- Custom Language Support / [Syntax and Error Highlighting](https://plugins.jetbrains.com/docs/intellij/syntax-highlighting-and-error-highlighting.html)
- Custom Language Support Tutorial / [5. Syntax Highlighter and Color Settings Page](https://plugins.jetbrains.com/docs/intellij/syntax-highlighter-and-color-settings-page.html)
